language: go

go:
  - "1.10"

# magic word to use faster/newer container-based architecture
sudo: false

addons:
  apt_packages:
    - graphicsmagick

services:
  - postgresql

cache:
  pip: true

notifications:
  email:
    on_success: never

install:
  - go get -u github.com/golang/lint/golint
  - pip install --user awscli

before_script:
  # Download only a minimal set of photo markers. This allows us to save time
  # by not redoing download/resize work, but also saves us build bandwidth
  # because we don't need to download the entire set of photos (only zero byte
  # marker files).
  #
  # Uses alternate readonly AWS credentials so it can work on non-master
  # builds.
  - make photos-download-markers

script:
  - VERBOSE=true make

  # deploy development version that includes drafts
  - TARGET_DIR=./public-dev DRAFTS=true make build
  - TARGET_DIR=./public-dev S3_BUCKET=brandur.org-dev make deploy

  # then deploy production
  - TARGET_DIR=./public S3_BUCKET=brandur.org make deploy

after_script:
  # Upload any photos that we processed during this build. This requires write
  # access, so it only works on the master branch where $AWS_ACCESS_KEY_ID is
  # available.
  - make photos-upload

# Env that allows a build on the master branch to deploy the site
# automatically.
env:
  global:
    - CLOUDFRONT_ID=E2D97SPIHRBCUA
    - GOOGLE_ANALYTICS_ID=UA-47798518-1

    # Use only a single Goroutine so that we can debug problems that arise more
    # easily. The build in CI is already lengthy due to system setup, and
    # shaving a few hundred milliseconds off with more concurrency makes almost
    # no difference at all.
    - CONCURRENCY=1

    # $AWS_ACCESS_KEY_ID
    - secure: "N7O3iKGp51NBnkrgAjNrVbtV2sxmiG8NY07oNVvkhzPRhdOSB+nXwhEk+K3Bz7AiC+2WGXBZRx2jvjDu3w3L9k4NnsEFtOlt+7BBcDUHt2xqLkQNBTj5k51F+3oCJPoBEzwL7Cb8YAzFhcVyrgp903R1oHy5F+fs+ICRkapID92/6yCpFt86O7tT6u7jsQuEtmc/uT5EQzy3h7A1zNnIReouHGx3ZLNKqdTObHrKHV2IILR9pI7TF/BZLHQ20uyQheoIz8B0MeGpPOK4AFNTt8L/qEp89HvymjFY90d40o1MXYPlOvDktYMXyJhtgMiDBkLgDyx8K7WMCMewoVj4bmBeyJSDrItoE6ErNCNYZccC0Zc2W9ePZOfxnDFNazNEbWeNutcSJbavndZ08tCqTyy8aUwsHOMtsAUWAqlVxUCx8f4brMpmjcRXrM8bEcUc1O+27yMk6Oixm+1I++CcGfLUV78PwgeTv0LZHRzqcggLh+vAUdN/AR4/Co1T0rcg2xeDFF4IqOTW9Y/3RV8/kL2CAgkkBy6WE4BgX2vIzsH/COj23wYq2OPFS2pRjopqBvraqNIJQ3GzZuQ2O39695XzRtwYCG9Hy/BOvWVMWBdttB/WqZL/YBXEoVq893UNAV5L7xfvZ5K+0HFfpwn36rtfkz6MeZ2mWNKjv3uA3/4="

    # $AWS_SECRET_ACCESS_KEY
    - secure: "ItEchoM+m5HqDlevV0rPScsO0VAwUdYxsorYz4EBfnjLRsMw9Sp3Awrd8OM/PbuFNLEFSioTNLe6GI7eggp1nsnSxUyhkiDqAYTQi46Kx3SbR8czkaokQLhpw9z5c2CdamnMjV7QSezD/YPafSVqXi/QjKiPgXS0BdlwKtQK2HAmHzUWj32/PFeoH8jRH5Kd7xfzgSZazxyNyQ+SKakY6VPaQYGRSZIi/uqFmuuI9VpPsX5R6RjpJgnqv3FQ0Bh8a8lj270NKygDBW4sDc9DOFgIBKQufrUOd/TZzudYd0+uwydjYEuO/3LN2fnIV/3MomdB5uD9B1Q5cAF2c/POkQ/TXgJryBRaEiA0tq9orws16G5iN0B6sEfEfCvpqNVkM59xuwjrwzkbuZ/w7SG4f8EKnctqh0Z7rh17OqfpRZhVNScnxOxI7fLeJ9Bu7OCUAa3wDLxTevmaJSKW3nv2M0iF9MkbU7hh5QDRGD1TX2AmFRk7grr0U5RvCl0ZJxm2XRBLtN8AO654qTQwhzpECDgaQlb7CUjkW3Eaysgob57pme2SC27I4EMA0AGHWf7k2uQrKesnl635KStyxAtmO/3hp7l2Se3U7RtMc2onYw1zhROJq/8sLWMZ3oNMTBC8rgVmrvtyH5Fd/xvOLT+ESiIb+d2EkZ8RwlGauE9Jby4="

    # $BLACK_SWAN_DATABASE_URL
    - secure: "obYt+fAcDKox/K6zN7cJsAqW2zZ/wGBfpyhZIP+hoGXWcyMqzby+bdK9SIczePALQz0ihtuabHa5rP4mPm/0A809Q6ccP4WeQRPNoqqeWwX9YYDeU7dp0C/bOxM/7ow4G+9FUaNp5hVlqZ4IKnVF3XmQkbxB4PsnCH0cV/qsF9foe1W7OWtCOLYWNTpfPbl8r6tfcl+MCzAn+SyBiLbLuVOPUhOTe7V1eCDPPpuC/qrA9djJ6fThrcyU9qeYCXMKU/8KdFIUGo96A2ro3JHfixaRSniupcaBPMvTRNcrd4CBhyfZ61PQEIos+GvJQiDX8jysg3UnASS2w3o2meZx4En2G4NCUEki0gq1plNuQIxDHpwpMr97k+WW4OpS05ZzwUBosOry1h94ppzkSNrsvVT2E+GKiieLXIj/dkawWsmiYs4VIRHVBgk1cjDcKaJm2FNYjgOcoYISvpw7aQYvIfvO9+LfeLCu2zAjw0ZZ0EaFO5AlHOogy9GAQZyaUrMmFl5I4QcZdD9hH3Dil0m7zo5RWWblyvhc4oQwhVBDg95kFpxd6ojAZ6IhjMRy8umtd/LSt0GBm9uW1Ci6CMV0H0IAySvZqtuHWjyXnByLhxFp6W5ujRlRCxGMRikw5zZ69trAT9PJcZEQ6uyB8b2XqRXQ48ErkbJ41AlRx6dWcOE="

before_script:
  - createdb sorg-test
