##############################################################################
#
#
# articles
#
#
##############################################################################

#
# size conventions:
#
#   * in-body overflowing images: 650 wide
#

#
# /minimal-analytics
#

[[photographs]]
crop_width = 650
original_image_url = "https://www.dropbox.com/s/qmut0530vvlxl2k/athena-query.png?dl=1"
slug = "articles/minimal-analytics/athena-query"
title = "Querying via Athena's UI."

[[photographs]]
crop_width = 650
original_image_url = "https://www.dropbox.com/s/92c4ac0e2pnvwfc/cloudfront-logging-wide.png?dl=1"
slug = "articles/minimal-analytics/cloudfront-logging"
title = "Configuring CloudFront logging."

[[photographs]]
crop_width = 650
original_image_url = "https://www.dropbox.com/s/g8v1s54epugva1z/goaccess.png?dl=1"
slug = "articles/minimal-analytics/goaccess"
title = "GoAccess' command line interface."

[[photographs]]
crop_width = 650
original_image_url = "https://www.dropbox.com/s/r3x2ljtrv22xd6z/goatcounter.png?dl=1"
slug = "articles/minimal-analytics/goatcounter"
title = "GoatCounter's measurement of an HN traffic peak."

[[photographs]]
crop_width = 650
original_image_url = "https://www.dropbox.com/s/04l2orptqa08kvd/s3-lifecycle-rules.png?dl=1"
slug = "articles/minimal-analytics/s3-lifecycle-rules"
title = "Creating an S3 lifecycle rule for expiration."

[[photographs]]
crop_width = 650
original_image_url = "https://www.dropbox.com/s/zjkkzi0yft117eu/ublock-origin.png?dl=1"
slug = "articles/minimal-analytics/ublock-origin"
title = "uBlock Origin blocking analytics sites."

##############################################################################
#
#
# fragments
#
#
##############################################################################

#
# size conventions:
#
#   * in-body images: 550 wide
#   * in-body overflowing images: 650 wide
#   * vistas: 1024 wide
#

#
# /fragments/engelmann-spruce-plaque-sulfur-mountain
#

[[photographs]]
crop_width = 1024
original_image_url = "https://www.dropbox.com/s/tvz4t4ggikrld6x/2W4A0178-cropped.jpg?dl=1"
slug = "fragments/engelmann-spruce-plaque-sulfur-mountain/plaque"
title = "Plaque naming an Englemann Spruce tree"

#
# /fragments/graceful-degradation-time
#

[[photographs]]
crop_width = 650
original_image_url = "https://www.dropbox.com/s/lupzf5ld2igqoup/markdown-and-git.png?dl=1"
slug = "fragments/graceful-degradation-time/markdown-and-git"
title = "Markdown and Git"

#
# /fragments/leica-q2-monochrom
#

[[photographs]]
crop_width = 650
original_image_url = "https://www.dropbox.com/s/w0pyp9ild0e3cfa/image-comparison.jpg?dl=1"
slug = "fragments/leica-q2-monochrom/image-comparison"
title = "Leica Q2 and Q2 Monochrom images compared"

[[photographs]]
crop_width = 650
original_image_url = "https://www.dropbox.com/s/dgr20h10fnskp5b/leica-q2.jpg?dl=1"
slug = "fragments/leica-q2-monochrom/leica-q2"
title = "The Leica Q2"

[[photographs]]
crop_width = 650
original_image_url = "https://www.dropbox.com/s/3cf94luaq80w73a/leica-q2-monochrom.jpg?dl=1"
slug = "fragments/leica-q2-monochrom/leica-q2-monochrom"
title = "The Leica Q2 Monochrom"

#
# /fragments/new-york
#

[[photographs]]
crop_width = 550
original_image_url = "https://www.dropbox.com/s/q2mpowmbriapnmc/DSCF4515.JPG?dl=1"
slug = "fragments/new-york/apple-store"
title = "5th Ave Apple Cube"

[[photographs]]
crop_width = 550
original_image_url = "https://www.dropbox.com/s/to4sgrv7ce6xeje/DSCF4769.JPG?dl=1"
slug = "fragments/new-york/dont-block-the-box"
title = "Don't block the box"

[[photographs]]
crop_width = 550
original_image_url = "https://www.dropbox.com/s/ppjs48o5d0otdyt/DSCF4613.JPG?dl=1"
slug = "fragments/new-york/met"
title = "The Met"

[[photographs]]
crop_width = 550
original_image_url = "https://www.dropbox.com/s/vazjg3v7lxjqdj2/DSCF4825.JPG?dl=1"
slug = "fragments/new-york/high-line"
title = "The High Line"

[[photographs]]
crop_width = 550
original_image_url = "https://www.dropbox.com/s/pyvzdfq33ejob1a/DSCF4767.JPG?dl=1"
slug = "fragments/new-york/rockefeller"
title = "Rockefeller"

[[photographs]]
crop_width = 550
original_image_url = "https://www.dropbox.com/s/a8o1y2g44f11oyz/DSCF4694.JPG?dl=1"
slug = "fragments/new-york/washington-square-park"
title = "Washington Square Park"

#
# /fragments/openai-api
#

[[photographs]]
crop_width = 650
original_image_url = "https://www.dropbox.com/s/v5okuhgt6334748/example.png?dl=1"
slug = "fragments/openai-api/example"
title = "An example API response from OpenAI"

[[photographs]]
crop_width = 650
original_image_url = "https://www.dropbox.com/s/wf047o5kxjik65m/openai-api-docs.png?dl=1"
slug = "fragments/openai-api/openai-api-docs"
title = "OpenAI API documentation"

#
# /fragments/rss-abandon
#

[[photographs]]
crop_width = 650
original_image_url = "https://www.dropbox.com/s/f5lmidlh0u74ozs/reeder.png?dl=1"
slug = "fragments/rss-abandon/reeder"
title = "Reeder screenshot"

#
# /fragments/safety-razors
#

[[photographs]]
crop_width = 550
original_image_url = "https://www.dropbox.com/s/yp5x0b0jt5yfi31/razor.jpg?dl=1"
slug = "fragments/safety-razors/razor"
title = "A safety razor"

#
# /fragments/wgt-2015-brain-dump
#

[[photographs]]
crop_width = 550
original_image_url = "https://www.dropbox.com/s/wly7tt7i45dq6el/jo-quail.jpg?dl=1"
slug = "fragments/wgt-2015-brain-dump/jo-quail"
title = "Jo Quail"

[[photographs]]
crop_width = 550
original_image_url = "https://www.dropbox.com/s/32kvs3gfcdawbbs/leaf.jpg?dl=1"
slug = "fragments/wgt-2015-brain-dump/leaf"
title = "L.E.A.F."

##############################################################################
#
#
# nanoglyphs
#
#
##############################################################################

#
# size conventions:
#
#   * landscape: 1200 wide
#   * portrait: 900 wide
#   * constrained (non photos): 600 wide
#

#
# /nanoglyphs/027-15-minutes
#

[[photographs]]
crop_width = 496 # original image only 992 wide
original_image_url = "https://www.dropbox.com/s/21t62z257f9tzxg/15-minute-tweet.png?dl=1"
slug = "nanoglyphs/027-15-minutes/15-minute-tweet"
title = "Tweet of 15 minutes to upgrade"

#
# /nanoglyphs/026-ids
#

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/qzcqqqe80kkwrpm/L1010861.jpg?dl=1"
slug = "nanoglyphs/026-ids/great-highway"
title = "Looking down the Great Highway"

[[photographs]]
crop_width = 900
original_image_url = "https://www.dropbox.com/s/bqx7qubthu3x5j5/2W4A0530.JPG?dl=1"
slug = "nanoglyphs/026-ids/pacifica"
title = "Pacifica"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/ysm5c94xch04bgv/2W4A0529.JPG?dl=1"
slug = "nanoglyphs/026-ids/pacifica-2"
title = "Pacifica"

[[photographs]]
crop_width = 900
original_image_url = "https://www.dropbox.com/s/6nmtr3aqa43upwz/L1020361.JPG?dl=1"
slug = "nanoglyphs/026-ids/salesforce-park"
title = "TODO"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/8wpcoxfnu4l5km6/san-bruno.png?dl=1"
slug = "nanoglyphs/026-ids/san-bruno"
title = "Walk to San Bruno"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/9x2vlfmna20ru1p/2W4A0555.JPG?dl=1"
slug = "nanoglyphs/026-ids/south-san-francisco"
title = "Sweeney Ridge"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/pqsqbw9bmeqwr5m/2W4A0541.JPG?dl=1"
slug = "nanoglyphs/026-ids/sweeney-ridge"
title = "Sweeney Ridge"

[[photographs]]
crop_width = 384 # original image only 768 wide
original_image_url = "https://www.dropbox.com/s/mfj8ih965izaevo/uuid-tps.png?dl=1"
slug = "nanoglyphs/026-ids/uuid-tps"
title = "Transactions per second comparison"

[[photographs]]
crop_width = 384 # original image only 768 wide
original_image_url = "https://www.dropbox.com/s/e0cbeluvlhace7u/uuid-wal-medium-normalized.png?dl=1"
slug = "nanoglyphs/026-ids/uuid-wal-medium-normalized"
title = "WAL size comparison"

#
# /nanoglyphs/025-logs
#

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/lhpfm4kofd2zbpa/2W4A0474.JPG?dl=1"
slug = "nanoglyphs/025-logs/heroes-grove"
title = "Redwoods in Heroes Grove, Golden Gate Park"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/1al3m62ns8mc3mv/2014-01-26-heroku-sign.jpg?dl=1"
slug = "nanoglyphs/025-logs/heroku-sign"
title = "Heroku sign at 650 7th"

[[photographs]]
crop_width = 350
original_image_url = "https://www.dropbox.com/s/sx8ho92svfwe3l6/lines-changed.png?dl=1"
slug = "nanoglyphs/025-logs/lines-changed"
title = "Number of lines changed"

[[photographs]]
crop_width = 350
original_image_url = "https://www.dropbox.com/s/lbwzseessuohtjh/lines-changed-2.png?dl=1"
slug = "nanoglyphs/025-logs/lines-changed-2"
title = "Number of lines changed"

[[photographs]]
crop_width = 600
original_image_url = "https://www.dropbox.com/s/5igneu0z0f49yo7/log-aggregates.png?dl=1"
slug = "nanoglyphs/025-logs/log-aggregates"
title = "Aggregating logs"

[[photographs]]
crop_width = 600
original_image_url = "https://www.dropbox.com/s/u6u2dv7gq99ejd5/log-clean-trace.png?dl=1"
slug = "nanoglyphs/025-logs/log-clean-trace"
title = "Clean trace of log lines"

[[photographs]]
crop_width = 600
original_image_url = "https://www.dropbox.com/s/m0lvf3v2vwvtyvh/log-expanded.png?dl=1"
slug = "nanoglyphs/025-logs/log-expanded"
title = "Log line expanded"

[[photographs]]
crop_width = 600
original_image_url = "https://www.dropbox.com/s/9t3pofbpmjuf0d5/log-nested-structures.png?dl=1"
slug = "nanoglyphs/025-logs/log-nested-structures"
title = "Nested structures in logs"

[[photographs]]
crop_width = 600
original_image_url = "https://www.dropbox.com/s/k4ftqsfh2u6u2ts/sentry-trace.png?dl=1"
slug = "nanoglyphs/025-logs/sentry-trace"
title = "Distributed Sentry trace"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/o2zr4b4e4kvuojn/03_93_27_04_BillyJohn.jpg?dl=1"
slug = "nanoglyphs/025-logs/03_93_27_04_BillyJohn"
title = "03_93_27_04_BillyJohn"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/y5c7tky7369svg1/04_96_35_20_HandsomeDave.jpg?dl=1"
slug = "nanoglyphs/025-logs/04_96_35_20_HandsomeDave"
title = "04_96_35_20_HandsomeDave"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/58kr8oipaasmyzr/05_93_18_22_Joe_and_messenger.jpg?dl=1"
slug = "nanoglyphs/025-logs/05_93_18_22_Joe_and_messenger"
title = "05_93_18_22_Joe_and_messenger"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/sr5z0l56we2i9hc/12_92_65_02_Chris.jpg?dl=1"
slug = "nanoglyphs/025-logs/12_92_65_02_Chris"
title = "12_92_65_02_Chris"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/dox7arcmpbumhyy/17_93_48_09_Anita.jpg?dl=1"
slug = "nanoglyphs/025-logs/17_93_48_09_Anita"
title = "17_93_48_09_Anita"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/8962gwu496vh1e9/21_95_49_06_Manny.jpg?dl=1"
slug = "nanoglyphs/025-logs/21_95_49_06_Manny"
title = "21_95_49_06_Manny"

#
# /nanoglyphs/024-new-horizons
#

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/yps66x5h69nr62n/2W4A0460.JPG?dl=1"
slug = "nanoglyphs/024-new-horizons/sunrise"
title = "Sunrise over Twin Peaks"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/n23ul6xjnvapups/2W4A0465.JPG?dl=1"
slug = "nanoglyphs/024-new-horizons/sunrise-tree"
title = "Sunrise towards downtown, through a tree"

#
# /nanoglyphs/023-enhancement
#

[[photographs]]
crop_width = 900
original_image_url = "https://www.dropbox.com/s/lqcz3psheoyuyi9/city-pop.jpg?dl=1"
slug = "nanoglyphs/023-enhancement/city-pop"
title = "Japanese city pop"

# [[photographs]]
#   crop_width = 1200
#   original_image_url = "https://www.dropbox.com/s/65des0t2jg86052/2W4A0399-hoop.JPG?dl=1"
#   slug = "nanoglyphs/023-enhancement/hoop"
#   title = "Basketball by Mount Sutro"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/sids26fjvpi2ona/2W4A0408.JPG?dl=1"
slug = "nanoglyphs/023-enhancement/sand"
title = "Sand"

#
# /nanoglyphs/022-entropy
#

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/n99y3gwwfv92xti/git.png?dl=1"
slug = "nanoglyphs/022-entropy/git"
title = "Sorg in Git"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/mtnly810xmz89kw/L1030975.JPG?dl=1"
slug = "nanoglyphs/022-entropy/yunomine"
title = "Yunomine Onsen"

[[photographs]]
crop_width = 900
original_image_url = "https://www.dropbox.com/s/mcoyfbtby6izw3t/L1040042.JPG?dl=1"
slug = "nanoglyphs/022-entropy/yunomine-2"
title = "Yunomine Onsen 2"

#
# /nanoglyphs/021-ides
#

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/omt60a0q4abj580/L1070842-chairlift.JPG?dl=1"
slug = "nanoglyphs/021-ides/chairlift"
title = "A chairlift off season"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/v9jbu6xrhmeo2dg/L1070841.JPG?dl=1"
slug = "nanoglyphs/021-ides/wind-turbine"
title = "A wind turbine near Vancouver"

#
# /nanoglyphs/019-api-libraries
#

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/j5ns5cht9vzjxez/2W4A0232.JPG?dl=1"
slug = "nanoglyphs/019-api-libraries/brickell"
title = "Around Brickell in Miami"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/daw7v9f42v8teic/wani-kani.png?dl=1"
slug = "nanoglyphs/019-api-libraries/wani-kani"
title = "Wani Kani's home page"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/vr9tvo4im3yh3zs/2W4A0289.JPG?dl=1"
slug = "nanoglyphs/019-api-libraries/vizcaya"
title = "The gardens at Vizcaya in Miami"

#
# /nanoglyphs/018-ractors
#

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/tvz4t4ggikrld6x/2W4A0178-cropped.jpg?dl=1"
slug = "nanoglyphs/018-ractors/engelmann-plaque"
title = "Plaque on Sulphur Mountain showing an Engelmann Spruce"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/yvhbe0c6wsydc4f/2W4A0150.JPG?dl=1"
slug = "nanoglyphs/018-ractors/sulphur-gondola"
title = "The gondola at Sulphur Mountain"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/0cf7x6o1ccew6qi/2W4A0161.JPG?dl=1"
slug = "nanoglyphs/018-ractors/sulphur-view"
title = "The view off Sulphur Mountain"

#
# /nanoglyphs/017-twenty
#

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/7jxx7zx7e3xalfb/2W4A0137.JPG?dl=1"
slug = "nanoglyphs/017-twenty/canmore"
title = "The mountains of Canmore"

[[photographs]]
crop_width = 900
original_image_url = "https://www.dropbox.com/s/q1acfqfnkecpixu/da-vinci.jpg?dl=1"
slug = "nanoglyphs/017-twenty/da-vinci"
title = "Da Vinci"

[[photographs]]
crop_width = 900
original_image_url = "https://www.dropbox.com/s/778i77mmyh5t8mj/2W4A0146.JPG?dl=1"
slug = "nanoglyphs/017-twenty/river"
title = "The Bow River"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/1onhi70nuy5q2qw/2W4A0144.JPG?dl=1"
slug = "nanoglyphs/017-twenty/river-2"
title = "The Bow River"

#
# /nanoglyphs/016-postgres-13
#

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/tuhjavbworvu2xi/L1020154.jpg?dl=1"
slug = "nanoglyphs/016-postgres-13/uc-berkeley-clock-tower"
title = "UC Berkeley, the birthplace of Postgres"

[[photographs]]
crop_width = 900
original_image_url = "https://www.dropbox.com/s/52vx77e7vbirrky/L1020152.JPG?dl=1"
slug = "nanoglyphs/016-postgres-13/uc-berkeley-grove"
title = "A grove at UC Berkeley"

#
# /nanoglyphs/015-ruby-typing
#

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/41c579a1dfm069f/IMG_1391.jpg?dl=1"
slug = "nanoglyphs/015-ruby-typing/cole-valley"
title = "Cole Valley around noon on Bladerunner day"

#
# /nanoglyphs/014-local-first
#

[[photographs]]
crop_width = 900
original_image_url = "https://www.dropbox.com/s/hd9rwpy1fdxa91o/IMG_0441.jpg?dl=1"
slug = "nanoglyphs/014-local-first/bunaken"
title = "Bunaken"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/0kephagafiou7hp/L1080319.JPG?dl=1"
slug = "nanoglyphs/014-local-first/coral-eye"
title = "Coral Eye's dive jetty on Bangka in Indonesia"

[[photographs]]
crop_width = 900
original_image_url = "https://www.dropbox.com/s/bal6cya3yel8u0o/sandman.jpg?dl=1"
slug = "nanoglyphs/014-local-first/sandman"
title = "Page from Sandman"

#
# /nanoglyphs/013-remote
#

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/lcr7oi8bicodhu8/L1010190.jpg?dl=1"
slug = "nanoglyphs/013-remote/great-highway"
title = "The Great Highway, car free"

[[photographs]]
crop_width = 900
original_image_url = "https://www.dropbox.com/s/s0zooun0rruvkz0/L1000514-crop-2.jpg?dl=1"
slug = "nanoglyphs/013-remote/slope"
title = "A steep San Francisco street"

#
# /nanoglyphs/011-shelter
#

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/81uhvmzbp8tspfd/L1000272.JPG?dl=1"
slug = "nanoglyphs/011-shelter/chimes"
title = "Wind chimes at home"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/uds1vfevcyxd1e8/L1000270.JPG?dl=1"
slug = "nanoglyphs/011-shelter/pool"
title = "Pool on the roof"

[[photographs]]
crop_width = 900
original_image_url = "https://www.dropbox.com/s/g56ancw989uv4lv/IMG_0846-crop.jpg?dl=1"
slug = "nanoglyphs/011-shelter/sutro-tower"
title = "Sutro Tower"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/6880e7vmtehjif1/L1000258.JPG?dl=1"
slug = "nanoglyphs/011-shelter/tea"
title = "Tea set -- made in Calgary and Japan"

#
# /nanoglyphs/010-monterey
#

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/fu9cjjbssl4kyby/L1080497.JPG?dl=1"
slug = "nanoglyphs/010-monterey/san-carlos"
title = "San Carlos Beach in Monterey at sunrise."

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/zsbf2sz8abw0lsy/mariana-trench.jpg?dl=1"
slug = "nanoglyphs/010-monterey/mariana-trench"
title = "The Mariana Trench"

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/vno7c26xsfopxww/L1080491.JPG?dl=1"
slug = "nanoglyphs/010-monterey/storefront"
title = "Storefront"

#
# /nanoglyphs/006-moma-rain
#

[[photographs]]
crop_width = 1200
original_image_url = "https://www.dropbox.com/s/ywcoofzdn2vhq53/L1080399.JPG?dl=1"
slug = "nanoglyphs/006-moma-rain/moma"
title = "The San Francisco MOMA"
