title = "Berlin"
description = """\
I first visited Berlin 2011, expecting a clean and efficient German capital. Not only was it neither of those things, but it swung far in the other direction, and I was charmed by its unique oddities -- ubiquitous graffiti, bars without defined closing times (usually open until 4 AM and later, if they close at all), and prodigious levels of open air beer consumption.

It's a city still in transition as it heals from the division that ended with the fall of Wall in '89, still a recent event by historical standards. A sordid history led to some good things, as a low cost of living and a glut of cheap real estate led to decades of blossoming art and creativity. From night clubs located in old power plants, to airports become public parks, to spas where you can relax to the sounds of hard techno -- for encountering the unexpected, there's no better place on Earth.

A few visits later it's still my favorite city, and I try to coax out a few new and interesting things whenever I visit. It's never hard.

See also some [background on the _Sequences_ project](/sequences-project).
\
"""

[[photographs]]
  occurred_at = 2019-06-09T08:56:50Z
  original_image_url = "https://www.dropbox.com/s/xyo86uxb0nie7oj/L1070488-wall.JPG?dl=1"
  slug = "001"
  title = "Grenzmauer 75"

  description = """\
The first few days of my stay are spent in Friedrichshain along the Spree. Jetlagged beyond belief, I take a walk at 5 AM and realize that I'm staying next to the longest continuous section of the [Berlin Wall](https://en.wikipedia.org/wiki/Berlin_Wall) that's still standing, known as the "East Side Gallery".

The wall, or officially the **Anti-Fascist Protection Rampart** by East Germany's GDR, wasn't built to repel invasion as the name suggests, but as an emergency effort to keep their own population in. Flight to the west was so bad that it was compromising the viability of the country's economy, with departees disproportionately of working age and professionally skilled.

Khrushchev and Ulbricht conspired to close the border in August 1961 despite the inevitable damage it would do to communism's PR. The wall started life as barbed wire entanglements on August 13th ("Barbed Wire Sunday") and a few refinements later would became the _Grenzmauer 75_ (Border Wall 1975) of 45,000 prefab concrete blocks that we recognize today.

**At the begining of 1989, GDR leader Erich Honecker predicted that the wall would stand stand strong for 50 or 100 more years**, but that same year, a refugee crisis pressured the East German government to revise crossing regulations with a provision for private round trips. Miscommunication in the party's hierarchy caused a spokesman to suggest that the new rules would come into effect immediately, when they were supposed to activate the following day to provide time for border guards to be briefed. Televised broadcasts prompted huge gatherings at the wall's six checkpoints demanding to cross. As pressure continued to build, the vastly outnumbered soldiers would eventually allow it as no one was willing to authorize the use of lethal force.

Since then, sections of the wall have been exported around the world and can be found [everywhere](https://en.wikipedia.org/wiki/List_of_Berlin_Wall_segments#Indonesia) from Manitoba to Indonesia to Estonia. Graffiti had been a common fixture on the west side of the wall for some time, but graffiti on its _east_ side, like that pictured below is new, appearing only after the '89 collapse.
\
"""

[[photographs]]
  occurred_at = 2019-06-10T10:33:37Z
  original_image_url = "https://www.dropbox.com/s/hq5on26kbnspeia/IMG_1058-cropped.jpg?dl=1"
  slug = "002"
  title = "Fire and water"

  description = """\
Back home packing, I waffle over whether I can get away without bringing a jacket. Finally, I decide to try it. I know it's risky, but keep it light.

Fast forward 24 hours: I land in a Berlin that's not only hot, but _so_ hot that the city is skimming temperature records, with daily highs like 34 degrees (93F). Thoughts of jackets are quickly forgotten; replaced with brainstorming on how to strip off as many layers as possible while avoiding arrest for public indecency.

Berlin has some amazing running routes, but this year even a few kilometers are oppressive. A painful workaround is to go early -- like _really_ early -- ideally 5:30 or so, when the mercury's "only" in the high teens/low twenties. Long daylight hours (the sun rises before 5 AM) combined with jet lag make the ambitious schedule possible.

This photo's of the wilderness along my favorite run -- follow the Spree southeast out of Friedrichshain, into northern Kreuzberg (say "hi" to the people still partying), passed the sunken [MS Dr. Ingrid Wengler](https://fotostrasse.com/abandoned-boat-spree-river/) and [Molecule Man](https://en.wikipedia.org/wiki/Molecule_Man_(sculpture\\)), through Treptower Park, and then south by and around the ruins of [Spreepark](https://www.abandonedberlin.com/2010/04/spreepark-and-how-to-get-in.html) (scroll down at that link for some great photos, and hundreds of anecdata points from people sneaking passed the fence). This year, the fallen tyrannosaurus is gone, but the creaking old ferris wheel still stands.
\
"""

[[photographs]]
  occurred_at = 2019-06-13T08:45:07Z
  original_image_url = "https://www.dropbox.com/s/zblfzngjam5n8w5/L1070542-cropped.jpg?dl=1"
  slug = "003"
  title = "Doom under the dome"

  description = """\
The _Volkspalast_ ("people's palace") is a big, circular space built under a dome to be reminiscent of [the Pantheon](https://en.wikipedia.org/wiki/Pantheon,_Rome) in Rome commissioned by Marcus Agrippa under Augustus' reign. With the honor system being the only thing that separates stage from crowd, the concerts held here are as intimate as you'll ever find.

This is Darkher performing her particular brand of slow doom metal, and there's no venue more appropriate for it (the original Pantheon wasn't available). It's the first day of [WGT](https://en.wikipedia.org/wiki/Wave-Gotik-Treffen) down in Leipzig, and I've hopped down here from Berlin for a few days to attend.
\
"""

[[photographs]]
  occurred_at = 2019-06-14T16:39:36Z
  original_image_url = "https://www.dropbox.com/s/f7up96ktcex7iv6/IMG_1084-cropped.jpg?dl=1"
  slug = "004"
  title = "Wild Leipzig"

  description = """\
Berlin has some nice parks and trails, but they pale compared to Leipzig's, which for money must be the running capital of Germany.

Head south out of the city center, through lively city parks containing beer gardens and stark Cold War era playgrounds. Help disoriented morning revelers still out from last night with directions back to their hotel. Follow the river. Notice how well-used paths turn to trails through tranquil forest smelling heavily of garlic ([collecting wild garlic](https://english.leipzig.de/services-and-administration/public-order-and-security/gathering-wild-garlic-in-leipzig/) is a signature activity of springtime Leipzig). Keep an eye out for overgrown cobblestone roads, abandoned tram lines, snails in the long grass, and wild boar (wild only in sense of the [species](https://en.wikipedia.org/wiki/Wild_boar) -- wisely fenced off).

Photo taken at my southermost reach near Agra -- just a few hundred feet from hundreds of tents housing sleeping festivalgoers at the WGT campground.
\
"""

[[photographs]]
  occurred_at = 2019-06-17T09:01:13Z
  original_image_url = "https://www.dropbox.com/s/c00ta7qzxnty16g/L1070510-adjusted.jpg?dl=1"
  slug = "005"
  title = "Moritzbastei"

  description = """\
Sometimes a series of historical accidents leads to something amazing that never could've been planned from the top down. Moritzbastei is one of those.

Originally the ancient city fortifications for Leipzig, it lost its military function during the [Seven Years' War](https://en.wikipedia.org/wiki/Seven_Years%27_War) and was relegated to storage. In 1974, the students club of the nearby University of Leipzig uncovered it and began a reabilitation project. The work took years and involved some 30,000 students -- among them a young physics student named Angela Merkel.

Today, it's a night club and cultural space inside a fortress, and runs from dusk until dawn every night of WGT. Photos often use optical tricks to make small places look larger, but this one does the opposite -- it's only a narrow glimpse into a huge space that spans a dozen rooms in a labyrinthine complex spanning many floors.
"""

[[photographs]]
  occurred_at = 2019-06-17T10:17:35Z
  original_image_url = "https://www.dropbox.com/s/lc6mfbysbqo5may/L1070554-westbad.JPG?dl=1"
  slug = "006"
  title = "Concerts in old pools"

  description = """\
One of the best parts of cities with long histories is the repurposing of derelict properties for more creative uses. Berlin, with artist squats in old department stores and night clubs in power plants, is the ultimate example of this sort of organic urban evolution in action. Leipzig isn't far behind.

One of the city's curious penchants is to convert old public pools into live music venues. Last year I ran into this in [Stadtbad](https://de.wikipedia.org/wiki/Stadtbad_(Leipzig\\)), Leipzig's old three wing central bath complex. This year: **Westbad**, the roof of which is pictured below -- a mix of amazing bath art, and modern metal frameworks to suspend speaker stacks. Taken during Escape With Romeo's show on the final night of WGT.
"""

[[photographs]]
  occurred_at = 2019-06-17T11:15:03Z
  original_image_url = "https://www.dropbox.com/s/t61cmdqzb2s8azu/L1070629-adjusted.jpg?dl=1"
  slug = "007"
  title = "Nordbahnhof"

  description = """\
Park auf dem Nordbahnhof ("Park on the Nordbahnhof") -- one of the more beautiful legacies of the wall. The area was originally part of a train line that led to the since demolished Nordbahnhof station. By 1961, the line was completely shut down as it became part of border fortifications for the new wall nearby. After the wall's collapse, it became a park.

It's highly reminiscent of New York's [High Line](https://en.wikipedia.org/wiki/High_Line), except with a more raw nature, fewer Blue Bottles, and *far* fewer people (finding green space in Berlin isn't quite the same level of competition as it is in New York). Similarly to the High Line, it's elevated three meters above the surrounding streets, and that vertical separation creates an effect of peaceful isolation from surrounding traffic.

I came across Nordbahnhof purely by accident as I was touring the area northwest of mitte, and was glad I did. Along the way: an overgrown rail bridge, old paving stones stacked into megalithic cubes, and the most dangerous-looking amusement park I've ever seen, complete with gutted cars suspended 80 feet in the air.
"""

[[photographs]]
  occurred_at = 2019-06-19T13:02:04Z
  original_image_url = "https://www.dropbox.com/s/6wiwkprubkth8dy/L1070739-cropped.jpg?dl=1"
  slug = "008"
  title = "Hot to enjoy a drink"

  description = """\
Some portraits of monkeys in the hot spring outside the rooftop Monkey Bar in the 25hours Hotel in Berlin. Yes, itâ€™s crappy Photoshop, but I don't care. Great concept. Great bar. I want to believe.

I previously published a section in [_Passages & Glass_](/newsletter) about going to see [Japanese macaques near Nagano](/passages/002-japan#macaques). It was amazing, even if as bad luck would have it, they weren't enjoying drinks at the time.
"""
